# -*- coding: utf-8 -*-
"""
Created on Fri Apr  8 10:40:20 2022

@author: atuo
"""

role_semantic = {
    "None": " the entity that is irrelevant to the event",
    "Place": " the place where the event takes place",
    "Time": " the time when the event takes place",
    "Life:Be-Born_Person": " the person who is born",
    "Life:Marry_Person": " the person who are married",
    "Life:Divorce_Person": " the person who are divorced",
    "Life:Injure_Agent": " the one that enacts the harm",
    "Life:Injure_Victim": " the harmed person",
    "Life:Injure_Instrument": " the device used to inflict the harm",
    "Life:Die_Agent": " the killer",
    "Life:Die_Victim": " the person who died",
    "Life:Die_Instrument": " the device used to kill",
    "Movement:Transport_Agent": " the agent responsible for the transport event",
    "Movement:Transport_Artifact": " the person doing the traveling or the artifact being transported",
    "Movement:Transport_Vehicle": " the vehicle used to transport the person or artifact",
    "Movement:Transport_Origin": " the place where the transporting originated",
    "Movement:Transport_Destination": " the place where the transporting is directed",
    "Transaction:Transfer-Ownership_Buyer": " the buying agent",
    "Transaction:Transfer-Ownership_Seller": " the selling agent",
    "Transaction:Transfer-Ownership_Beneficiary": " the agent that benefits from the transaction",
    "Transaction:Transfer-Ownership_Artifact": " the item or organization that was bought or sold",
    "Transaction:Transfer-Money_Giver": " the donating agent",
    "Transaction:Transfer-Money_Recipient": " the recipient agent",
    "Transaction:Transfer-Money_Beneficiary": " the agent that benefits from the transfer",
    "Business:Start-Org_Agent": " the founder",
    "Business:Start-Org_Org": " the organization that is started",
    "Business:Merge-Org_Org": " the organizations that are merged",
    "Business:Declare-Bankruptcy_Org": " the organization declaring bankruptcy",
    "Business:End-Org_Org": " the organization that is ended",
    "Conflict:Attack_Attacker": " the attacking agent",
    "Conflict:Attack_Target": " the target of the attack",
    "Conflict:Attack_Instrument": " the instrument used in the attack",
    "Conflict:Demonstrate_Entity": " the demonstrating agent",
    "Contact:Meet_Entity": " the agents who are meeting",
    "Contact:Phone-Write_Entity": " the communicating agent",
    "Personnel:Start-Position_Person": " the employee",
    "Personnel:Start-Position_Entity": " the employer",
    "Personnel:End-Position_Person": " the employee",
    "Personnel:End-Position_Entity": " the employer",
    "Personnel:Elect_Person": " the person elected",
    "Personnel:Elect_Entity": " the voting agent",
    "Personnel:Nominate_Person": " the person nominated",
    "Personnel:Nominate_Agent": " the nominating agent",
    "Justice:Arrest-Jail_Person": " the person who is jailed or arrested",
    "Justice:Arrest-Jail_Agent": " the jailer or the arresting agent",
    "Justice:Release-Parole_Person": " the person who is released",
    "Justice:Release-Parole_Entity": " the former captor agent",
    "Justice:Trial-Hearing_Defendant": " the agent on trial",
    "Justice:Trial-Hearing_Prosecutor": " the prosecuting agent",
    "Justice:Trial-Hearing_Adjudicator": " the judge or court",
    "Justice:Charge-Indict_Defendant": " the agent that is indicted",
    "Justice:Charge-Indict_Prosecutor": " the agent bringing charges or executing the indictment",
    "Justice:Charge-Indict_Adjudicator": " the judge or court",
    "Justice:Sue_Plaintiff": " the suing agent",
    "Justice:Sue_Defendant": " the agent being sued",
    "Justice:Sue_Adjudicator": " the judge or court",
    "Justice:Convict_Defendant": " the convicted agent",
    "Justice:Convict_Adjudicator": " the judge or court",
    "Justice:Sentence_Defendant": " the agent who is sentenced",
    "Justice:Sentence_Adjudicator": " the judge or court",
    "Justice:Fine_Entity": " the entity that was fined",
    "Justice:Fine_Adjudicator": " the entity doing the fining",
    "Justice:Execute_Person": " the person executed",
    "Justice:Execute_Agent": " the agent responsible for carrying out the execution",
    "Justice:Extradite_Person": " the person being extradicted",
    "Justice:Extradite_Agent": " the extraditing agent",
    "Justice:Extradite_Origin": " the original location of the person being extradited",
    "Justice:Extradite_Destination": " the place where the person is extradited to",
    "Justice:Acquit_Defendant": " the agent being acquitted",
    "Justice:Acquit_Adjudicator": " the judge or court",
    "Justice:Pardon_Defendant": " the agent being pardoned",
    "Justice:Pardon_Adjudicator": " the state official who does the pardoning",
    "Justice:Appeal_Defendant": " the defendant",
    "Justice:Appeal_Adjudicator": " the judge or court",
    "Justice:Appeal_Plaintiff": " the appealing agent",
}


event_role = {
    "Life:Be-Born": ["Person", "Place", "Time", "None"],
    "Life:Marry": ["Person", "Place", "Time", "None"],
    "Life:Divorce": ["Person", "Place", "Time", "None"],
    "Life:Injure": ["Agent", "Victim", "Instrument", "Place", "Time", "None"],
    "Life:Die": ["Agent", "Victim", "Instrument", "Place", "Time", "None"],
    "Movement:Transport": [
        "Agent",
        "Artifact",
        "Vehicle",
        "Price",
        "Origin",
        "Destination",
        "Time",
        "None",
    ],
    "Transaction:Transfer-Ownership": [
        "Buyer",
        "Seller",
        "Beneficiary",
        "Artifact",
        "Price",
        "Place",
        "Time",
        "None",
    ],
    "Transaction:Transfer-Money": [
        "Giver",
        "Recipient",
        "Beneficiary",
        "Money",
        "Place",
        "Time",
        "None",
    ],
    "Business:Start-Org": ["Agent", "Org", "Place", "Time", "None"],
    "Business:Merge-Org": ["Org", "Place", "Time", "None"],
    "Business:Declare-Bankruptcy": ["Org", "Place", "Time", "None"],
    "Business:End-Org": ["Org", "Place", "Time", "None"],
    "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Time", "None"],
    "Conflict:Demonstrate": ["Entity", "Place", "Time", "None"],
    "Contact:Meet": ["Entity", "Place", "Time", "None"],
    "Contact:Phone-Write": ["Entity", "Time", "None"],
    "Personnel:Start-Position": [
        "Person",
        "Entity",
        "Position",
        "Place",
        "Time",
        "None",
    ],
    "Personnel:Nominate": ["Person", "Agent", "Position", "Place", "Time", "None"],
    "Personnel:Elect": ["Person", "Entity", "Position", "Place", "Time", "None"],
    "Personnel:End-Position": ["Person", "Agent", "Crime", "Place", "Time", "None"],
    "Justice:Release-Parole": ["Person", "Entity", "Crime", "Place", "Time", "None"],
    "Justice:Trial-Hearing": [
        "Defendant",
        "Prosecutor",
        "Adjudicator",
        "Crime",
        "Place",
        "Time",
        "None",
    ],
    "Justice:Charge-Indict": [
        "Defendant",
        "Prosecutor",
        "Adjudicator",
        "Crime",
        "Place",
        "Time",
        "Sentence",
        "None",
    ],
    "Justice:Sue": [
        "Plaintiff",
        "Defendant",
        "Adjudicator",
        "Crime",
        "Place",
        "Time",
        "None",
    ],
    "Justice:Convict": ["Defendant", "Adjudicator", "Crime", "Place", "Time", "None"],
    "Justice:Sentence": [
        "Defendant",
        "Adjudicator",
        "Crime",
        "Sentence",
        "Place",
        "Time",
        "None",
    ],
    "Justice:Fine": [
        "Entity",
        "Adjudicator",
        "Money",
        "Crime",
        "Place",
        "Time",
        "None",
    ],
    "Justice:Execute": ["Person", "Agent", "Crime", "Place", "Time", "None"],
    "Justice:Extradite": [
        "Agent",
        "Person",
        "Destination",
        "Origin",
        "Crime",
        "Time",
        "None",
    ],
    "Justice:Acquit": ["Defendant", "Adjudicator", "Crime", "Place", "Time", "None"],
    "Justice:Pardon": ["Defendant", "Adjudicator", "Crime", "Place", "Time", "None"],
    "Justice:Appeal": [
        "Defendant",
        "Prosecutor",
        "Adjudicator",
        "Crime",
        "Place",
        "Time",
        "None",
    ],
    "Justice:Arrest-Jail": [
        "Person",
        "Agent",
        "Place",
        "Time",
        "None",
    ],
}

# all the roles in the dataset
all_roles = [
    "Adjudicator",
    "Agent",
    "Artifact",
    "Attacker",
    "Beneficiary",
    "Buyer",
    "Crime",
    "Org",
    "Defendant",
    "Destination",
    "Entity",
    "Instrument",
    "Origin",
    "Person",
    "Plaintiff",
    "Place",
    "Prosecutor",
    "Recipient",
    "Sentence",
    "Seller",
    "Target",
    "Time",
    "Vehicle",
    "Price",
    "Position",
    "Victim",
    "Giver",
    "None",
]  # 28/27 roles

# Entity type constraints for each role
role_entity_type_constraint = {
    "BE-BORN": {"person": ["PER"], "place": ["GPE", "LOC", "FAC"], "time": ["TIME"]},
    "MARRY": {"person": ["PER"], "place": ["GPE", "LOC", "FAC"], "time": ["TIME"]},
    "DIVORCE": {"person": ["PER"], "place": ["GPE", "LOC", "FAC"], "time": ["TIME"]},
    "INJURE": {
        "agent": ["PER", "ORG", "GPE"],
        "victim": ["PER"],
        "instrument": ["WEA", "VEH"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "DIE": {
        "agent": ["PER", "ORG", "GPE"],
        "victim": ["PER"],
        "instrument": ["WEA", "VEH"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "TRANSPORT": {
        "agent": ["PER", "ORG", "GPE"],
        "artifact": ["PER", "WEA", "VEH"],
        "vehicle": ["VEH"],
        "price": ["NUM"],
        "origin": ["GPE", "LOC", "FAC"],
        "destination": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "TRANSFER-OWNERSHIP": {
        "buyer": ["PER", "ORG", "GPE"],
        "seller": ["PER", "ORG", "GPE"],
        "beneficiary": ["PER", "ORG", "GPE"],
        "artifact": ["WEA", "VEH", "FAC", "ORG"],
        "price": ["NUM"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "TRANSFER-MONEY": {
        "giver": ["PER", "ORG", "GPE"],
        "recipient": ["PER", "ORG", "GPE"],
        "beneficiary": ["PER", "ORG", "GPE"],
        "money": ["NUM"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "START-ORG": {
        "agent": ["PER", "ORG", "GPE"],
        "org": ["ORG"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "MERGE-ORG": {"org": ["ORG"], "place": ["GPE", "LOC", "FAC"], "time": ["TIME"]},
    "DECLARE-BANKRUPTCY": {
        "org": ["ORG", "PER", "GPE"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "END-ORG": {"org": ["ORG"], "place": ["GPE", "LOC", "FAC"], "time": ["TIME"]},
    "ATTACK": {
        "attacker": ["PER", "ORG", "GPE"],
        "target": ["PER", "ORG", "FAC", "WEA", "VEH"],
        "instrument": ["VEH", "WEA"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "DEMONSTRATE": {
        "entity": ["PER", "ORG"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "MEET": {
        "entity": ["PER", "ORG", "GPE"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "PHONE-WRITE": {"entity": ["PER", "ORG", "GPE"], "time": ["TIME"]},
    "START-POSITION": {
        "person": ["PER"],
        "entity": ["ORG", "GPE"],
        "position": ["JOB"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "END-POSITION": {
        "person": ["PER"],
        "entity": ["ORG", "GPE"],
        "position": ["JOB"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "NOMINATE": {
        "person": ["PER"],
        "agent": ["PER", "ORG", "GPE", "FAC"],
        "position": ["JOB"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "ELECT": {
        "person": ["PER"],
        "entity": ["PER", "ORG", "GPE"],
        "position": ["JOB"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "ARREST-JAIL": {
        "person": ["PER"],
        "agent": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "RELEASE-PAROLE": {
        "person": ["PER"],
        "entity": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "TRIAL-HEARING": {
        "defendant": ["PER", "ORG", "GPE"],
        "prosecutor": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "CHARGE-INDICT": {
        "defendant": ["PER", "ORG", "GPE"],
        "prosecutor": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
        "sentence": ["SEN"],
    },
    "SUE": {
        "plaintiff": ["PER", "ORG", "GPE"],
        "defendant": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "CONVICT": {
        "defendant": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "SENTENCE": {
        "defendant": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "sentence": ["SEN"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "FINE": {
        "entity": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "money": ["NUM"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "EXECUTE": {
        "person": ["PER"],
        "agent": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "EXTRADITE": {
        "agent": ["PER", "ORG", "GPE"],
        "person": ["PER"],
        "destination": ["GPE", "LOC", "FAC"],
        "origin": ["GPE", "LOC", "FAC"],
        "crime": ["CRIME"],
        "time": ["TIME"],
    },
    "ACQUIT": {
        "defendant": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "PARDON": {
        "defendant": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
    "APPEAL": {
        "defendant": ["PER", "ORG", "GPE"],
        "prosecutor": ["PER", "ORG", "GPE"],
        "adjudicator": ["PER", "ORG", "GPE"],
        "crime": ["CRIME"],
        "place": ["GPE", "LOC", "FAC"],
        "time": ["TIME"],
    },
}
